### ISSUE TITLE
Support 'to not contain' tests

### ISSUE THREAD

**Issue by thecapdan** [bruderstein/unexpected-react-shallow#10]
It would be nice if it was possible to write inverse expectations.

For example,

```
expect(renderer, 'to not contain', <UnwantedNode/>)
```

**Comment by bruderstein** [comment]
Yes, it's on the todo list - should be really easy too.
I think the unexpected standard is the `not` at the start:

``` js
expect(renderer, 'not to contain', <UnwantedNode />);
```

**Comment by thecapdan** [comment]
Great, thanks Dave

**Comment by dchambers** [comment]
+1 for this :+1:

**Comment by bruderstein** [comment]
Just to say, this is coming. I'm almost ready with a completely new version. More news over the next day or 3 :-)

**Comment by richtier** [comment]
@bruderstein any news on this?

**Comment by bruderstein** [comment]
This is supported in [unexpected-react](https://github.com/bruderstein/unexpected-react). 

I'll be deprecating this library in favour of unexpected-react shortly. Unexpected-react supports  better output, and can optionally test against the virtual DOM, not just the shallow renderer (although it works with the shallow renderer just as well.  It also allows inline assertions (using `expect.it`), so you can validate a prop value matches a regular expression, for example.

The only reason to still use unexpected-react-shallow, is that it's still faster. I'm basically finished fixing that, so that unexpected-react will be almost as fast as unexpected-react-shallow (although it will never be 100% as fast, due to the extra features, like wrapper detection).

Once the new version of unexpected-react is released, I'll deprecate this library.
